name: f8n
description: Foundation library to Dart and Flutter applications.
version: 1.0.0
homepage: https://flutuate.io/

environment:
  #sdk: '>=2.12.0 <3.0.0'
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  intl: ^0.17.0
  simply_injector: ^1.1.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

#flutter:
  #assets:
    #- assets/
    #- assets/locale/
#--------------------------------------------------------------------------------------------------------
#
# Testes unitários:
# (--no-sound-null-safety evita o erro "Cannot run with sound null safety as one or more dependencies do not support null safety"):
#
#   flutter test --enable-experiment=non-nullable --no-sound-null-safety [path]
#
#   dart run --enable-experiment=non-nullable [path]
#
#   dart test --enable-experiment=non-nullable [path]
#
#--------------------------------------------------------------------------------------------------------
#
# Testes de integração:
#
# flutter run --enable-experiment=non-nullable [path]
#
#--------------------------------------------------------------------------------------------------------
#
# Analisar código:
#
# dartanalyzer -v --enable-experiment=non-nullable [path]
#
#--------------------------------------------------------------------------------------------------------
#
# Formatar fontes:
#
# dartfmt -w <path>
#
#--------------------------------------------------------------------------------------------------------
